### ISSUE TITLE
KeyError: 'PositionalEncoding'

### ISSUE THREAD

**Issue by LehaoLin** [torch2circom/torch2circom#1]
On Mac OS 13.5.1, M2 Pro
Python 3.9.6
Nodejs v20.11.1
Run
`python3 main.py models/best_practice.pth`
Get Error
```
Traceback (most recent call last):
  File "torch2circom/main.py", line 27, in <module>
    main()
  File "torch2circom/main.py", line 22, in main
    transpiler.transpile(args["--output"])
  File "torch2circom/torch2circom/transpiler.py", line 60, in transpile
    circuit.add_components(transpile_layer(layer))
  File "torch2circom/torch2circom/transpiler.py", line 96, in transpile_layer
    return transpile_pe(layer)
  File "torch2circom/torch2circom/transpiler.py", line 192, in transpile_pe
    templates["PositionalEncoding"],
KeyError: 'PositionalEncoding'
```

**Comment by LehaoLin** [comment]
After add git submodule
`https://github.com/torch2circom/circomlib-ml`
The issue solved

**Comment by LehaoLin** [comment]
Suggestion: to add git submodule correctly
`git submodulde add https://github.com/torch2circom/circomlib-ml`

**Comment by 000wan** [comment]
Thanks for reporting! I'll fix it.
